### ISSUE TITLE
Meta references across models fail to generate

### ISSUE THREAD

**Issue by davidalk** [finos/rune-dsl#812]
Given the following two pieces of Rosetta which reference each other in a parent child model relationship:

```Haskell
namespace model1
			
type Foo:
```

```Haskell
namespace model2
			
import model1.Foo
			
type Bar:
	foo Foo (1..1)
        [metadata reference]
```

Roseta Configuration for model1:
```yaml
model:
  name: My test model
dependencies:
generators:
  namespaces:
  - model1.*
  - com.rosetta.model
```

Roseta Configuration for model2:
```yaml
model:
  name: My test model
dependencies:
generators:
  namespaces:
  - model2.*
  - com.rosetta.model
```

In the above scenario the field `foo` will not generate the Meta Reference type whilst working on `model2`. This is because the type `Foo` exists in `model1` which is filtered by `model2` configuration. We need a way to recognise when meta needs to be generated for a link accross models such as this.
